title: coo11's start page

images:

bookmark:
  - name: Gmail
    url: https://inbox.google.com/
    favicon: gmail.png
  - name: QQ邮箱
    url: https://mail.qq.com
    favicon: qqmail.png
  - name: Outlook
    url: https://outlook.live.com/mail/0/inbox
    favicon: outlook.png
  - name: 163邮箱
    url: https://mail.163.com/
    favicon: netease163.png
  # - name: YandexMail
  #   url: https://mail.yandex.com/
  # - name: Google Earth
  #   url: https://earth.google.com/web/
  # - name: Google Maps
  #   url: https://www.google.com/maps/
  - name: Wikipedia
    url: https://zh.wikipedia.org/zh-hans/Wikipedia:%E9%A6%96%E9%A1%B5
    favicon: wikipedia.png
  - name: Youtube
    url: https://www.youtube.com
    favicon: youtube.png
  - name: 哔哩哔哩
    url: https://t.bilibili.com
    #  url: https://search.bilibili.com/all
    favicon: bilibili.png
  - name: GitHub
    url: https://github.com
    favicon: github.png
    faviconAlt: github_d.png
  - name: Notion
    url: https://www.notion.so/
    favicon: notion.png
  - name: Telegram
    #  url: https://web.telegram.org/k/
    url: https://web.telegram.org/a/
    favicon: telegram.png
  - name: 微信
    url: https://wx2.qq.com
    favicon: wechat2.png
  - name: DeepL
    url: https://www.deepl.com/translator
    favicon: deepl.png
    faviconAlt: deepl_d.png
  - name: 谷歌翻译
    url: https://translate.google.com/
    favicon: googletranslate.png
  - name: 百度翻译
    url: https://fanyi.baidu.com/
    favicon: baidutranslate.png

  - category: Shortcuts
  - name: MSN天气
    url: https://www.msn.com/zh-cn/weather/forecast
    favicon: msn.png
  - name: 文件传输助手
    url: https://szfilehelper.weixin.qq.com
    favicon: wechat.png
  - name: Rentry.co
    url: https://rentry.co/m5
    favicon: rentryco.png
  - name: Paste.ee
    url: https://paste.ee/
  # - name: Telegraph
  #   url: https://telegra.ph
  # - name: GIR
  #   url: https://coo11.github.io/gir/
  #   favicon: pic.png
  - name: QRCode
    url: https://mazhuren.com
    favicon: qrcode.png
  - name: Netcut
    url: https://netcut.cn/
    favicon: netcut.png
    faviconAlt: netcut_d.png
  - name: <b>More</b>
    newTab: true
    url: https://rentry.co/g1
    favicon: more.png

  - category: SNS
  - name: Twitter
    url: https://x.com/home
    favicon: twitter.png
    faviconAlt: twitter_d.png
  - name: 微博
    url: https://weibo.com
    favicon: sinaweibo.png
  - name: Discord
    url: https://discord.com/channels/@me
    favicon: discord.png
  - name: TikTok
    url: https://www.tiktok.com
    favicon: tiktok.png
  - name: Twitch
    url: https://www.twitch.tv
    favicon: twitch.png
  - name: 虎牙
    url: https://www.huya.com
    favicon: huya.png
  - name: 斗鱼
    url: https://www.douyu.com
    favicon: douyu.png
  - name: LOFTER
    url: https://www.lofter.com/
    favicon: lofter.png

  - category: Forum
  - name: NGA
    url: https://bbs.nga.cn
    favicon: nga.png
  - name: V2EX
    url: https://cn.v2ex.com/?tab=all
    favicon: v2ex.png
  - name: reddit
    url: https://www.reddit.com
    favicon: reddit.png
  # - name: 4chan
  #   url: https://www.4chan.org
  # - name: Два.ч
  #   url: https://2ch.hk
  - name: Steam
    url: https://store.steampowered.com/
    # url: https://steamcommunity.com
    favicon: steam.png
  - name: PCbeta
    url: http://bbs.pcbeta.com/forum.php
    favicon: pcbeta.png
  - name: Stage1st
    url: https://bbs.saraba1st.com/2b/forum-75-1.html
    # url: https://bbs.saraba1st.com/2b/forum.php
    favicon: stage1st.png
  - name: 知乎
    url: https://www.zhihu.com
    favicon: zhihu.png
  # - name: ExcelHome
  #   url: http://club.excelhome.net/forum.php
  # - name: 吾爱破解
  #   url: https://www.52pojie.cn
  - name: Hacker News
    url: https://news.ycombinator.com/
    favicon: hackernews.png
  # - name: 看雪
  #   url: https://bbs.kanxue.com/
  - name: 茶馆
    url: https://bbs.imoutolove.me/thread.php?fid-9.html
    favicon: soulplus.png

  - category: LLM
  - name: ChatGPT
    url: https://chatgpt.com/
    favicon: chatgpt.png
  - name: DeepSeek
    url: https://chat.deepseek.com/
    favicon: deepseek.png
  - name: Gemini
    url: https://gemini.google.com/app
    favicon: gemini.png
  # - name: 通义千问
  #   url: https://tongyi.aliyun.com/qianwen/
  - name: Qwen
    url: https://chat.qwen.ai/
    favicon: qwen.png
  - name: Claude
    url: https://claude.ai/
    favicon: claude.png
    faviconAlt: claude_d.png
  - name: MistralAI
    url: https://chat.mistral.ai/
    favicon: mistralai.png
  - name: Copilot
    url: https://edgeservices.bing.com/edgesvc/chat?clientscopes=chat,moblike,mobfull
    # url: https://chat.bing.com
    favicon: mscopilot.png
  - name: 文心一言
    url: https://yiyan.baidu.com/
    favicon: yiyan.png
  - name: Poe
    url: https://poe.com/
    favicon: poe.png
    faviconAlt: poe_d.png
  - name: LMSYS Arena
    url: https://chat.lmsys.org/
    favicon: gradio.png

  - category: Dev
  - name: StackOverflow
    url: https://stackoverflow.com
    favicon: stackoverflow.png
  - name: Hugging Face
    url: https://huggingface.co/
    favicon: huggingface.png
  # - name: SuperUser
  #   url: https://superuser.com
  # - name: MDN
  #   url: https://developer.mozilla.org/zh-CN/docs/Learn
  - name: RegExr
    url: https://regexr.com
    favicon: regexr.png
  - name: JSFiddle
    url: https://jsfiddle.net
    favicon: jsfiddle.png
    faviconAlt: fofa_d.png
  - name: GitLab
    url: https://gitlab.com
    favicon: gitlab.png
  - name: VSCode
    url: https://vscode.dev/
    favicon: vscode.png
  - name: CanIUse
    url: https://caniuse.com/
  - name: Carbon
    url: https://carbon.now.sh
  - name: Minifier
    url: https://hm.ehhh.eu.org/
    favicon: terser.png
  - name: CyberChef
    url: https://gchq.github.io/CyberChef/
    favicon: cyberchef.png
  - name: JSON Editor
    url: https://jsoneditoronline.com/
    favicon: json.png
    faviconAlt: json_d.png
  - name: REQBIN
    url: https://reqbin.com/
    favicon: reqbin.png
  - name: <b>More</b>
    newTab: true
    url: https://rentry.co/idev
    favicon: more.png

  - category: Search
  - name: Google
    url: https://www.google.com/ncr
    favicon: google.png
    faviconAlt: google_d.png
  - name: Yandex搜图
    url: https://yandex.com/images/
    favicon: yandeximage.png
  # - name: Google 图片
  #   url: https://images.google.com
  #   favicon: google.png
  # - name: 百度识图
  #   url: https://image.baidu.com/?fr=shitu
  #   favicon: baidu.png
  - name: Bing
    url: https://www.bing.com
    favicon: bing.png
  - name: WolframAlpha
    url: https://www.wolframalpha.com/
    favicon: wolframalpha.png
  - name: Startpage
    url: https://startpage.com
  - name: SauceNAO
    url: https://saucenao.com
    favicon: saucenao.png
  - name: ASCII2D
    url: https://ascii2d.net
  # - name: IQDB
  #   url: https://iqdb.org/
  # - name: Twitter 高级搜索
  #   url: https://twitter.com/search-advanced
  #   favicon: twitter.png
  - name: Google学术
    url: https://scholar.google.com
    favicon: googlescolar.png
  - name: WAIT
    url: https://trace.moe/
  - name: 搜图Bot酱
    url: https://soutubot.moe/
  - name: AnimeTrace
    url: https://ai.animedb.cn/

  - category: Utils
  - name: GVoice
    url: https://voice.google.com/messages
    favicon: googlevoice.png
  - name: Inoreader
    url: https://jp.inoreader.com/zh-hans/
    favicon: inoreader.png
  - name: SYMBL
    url: https://symbl.cc/cn/unicode-table/
    favicon: symbl.png
    faviconAlt: symbl_d.png
  - name: Dropmail
    url: https://dropmail.me/zh/
    favicon: at.png
  - name: TableConvert
    url: https://tableconvert.com
    favicon: tableconvert.png
  - name: FOFA
    url: https://fofa.info/
    favicon: fofa.png
  - name: IP
    url: https://ip.skk.moe/
    favicon: ip.png
  - name: InternetArchive
    url: https://archive.org/web/
    favicon: internetarchive.png
    faviconAlt: internetarchive_d.png
  - name: Archive.today
    url: https://archive.is
  - name: ウェブ魚拓
    url: https://megalodon.jp/
  - name: AriaNg
    # Search instances: https://www.google.com/search?q=0.00+B%2Fs+AriaNg
    # url: http://ariang.mayswind.net/latest/#!/settings/rpc/set/http/127.0.0.1/6800/jsonrpc
    # url: http://www.ykamc.cn/#!/settings/rpc/set/http/127.0.0.1/6800/jsonrpc
    # url: http://aria2.iloli.li/#!/settings/rpc/set/http/127.0.0.1/6800/jsonrpc
    url: javascript:(()=%3E%7Bvar%20t=prompt(%22RPC%20Config:%22,%22http/127.0.0.1/6800%22);t&&(location.href=%22http://ariang.mayswind.net/latest/#!/settings/rpc/set/%22+t+%22/jsonrpc%22)%7D)();
    favicon: downarrow.png
  - name: PaperSizes
    url: https://papersizes.io
  # - name: CloudConvert
  #   url: https://cloudconvert.com
  - name: iLovePDF
    url: https://www.ilovepdf.com/zh-cn
    favicon: ilovepdf.png
  - name: HTML2MD
    url: https://www.helloworld.net/html2md
    # url: https://tool.lu/markdown/
    favicon: helloworld.png
  - name: HTML Cleaner
    url: https://html-cleaner.com
  - name: r12a
    url: https://r12a.github.io/app-encodings/
  - name: Speedtest
    url: https://test.ustc.edu.cn/
    # Nanjing University Speed Test
    # url: https://test.nju.edu.cn/
    # 移动业务速率测试平台
    # url: http://speed.bj.10086.cn:3060/
    # 广东电信宽带测速平台
    # url: https://10000.gd.cn/#/speed
  - name: 文本对比
    url: https://diffsuite.com/zh/
  - name: <b>Index</b>
    newTab: true
    url: https://t.ehhh.eu.org/
    favicon: pokeball.png

  - category: Consume
  - name: 京东
    url: https://search.jd.com
    favicon: jingdong.png
  - name: 淘宝
    url: https://search.taobao.com
    favicon: taobao.png
  - name: 闲鱼
    url: https://2.taobao.com
  - name: 饿了么
    url: https://h5.ele.me
    favicon: eleme.png
  - name: 美团
    url: https://h5.waimai.meituan.com/waimai/mindex/home
    favicon: meituanwaimai.png
  - name: 1688
    url: https://search.1688.com
    favicon: alibaba.png
  - name: 唯品会
    url: https://www.vip.com/
    favicon: vipcom.png
  - name: Amazon
    url: https://www.amazon.co.jp
    favicon: amazon.png
  - name: 什么值得买
    url: https://www.smzdm.com
    favicon: smzdm.png

  - category: Image
  - name: PixFix
    url: https://zh.pixfix.com
    favicon: pixfix.png
  - name: waifu2x
    url: https://www.waifu2x.net/index.zh-CN.html
  # - name: TinyPNG
  # url: https://tinypng.com
  - name: PhotoFun
    url: https://www.photofun.cn/compress/
  - name: Watermark
    url: https://watermark.yycc.dev/ # https://github.com/funnyzak/watermark
  - name: EZGIF
    url: https://ezgif.com
  - name: ImgOps
    url: https://imgops.com
  - name: Unsplash
    url: https://unsplash.com/
    favicon: unsplash.png
    faviconAlt: unsplash_d.png
  - name: BoxySVG
    url: https://boxy-svg.com/app

  - category: Cloud Service
  - name: 坚果云
    url: https://www.jianguoyun.com
    favicon: jianguoyun.png
  - name: iCloud
    url: https://www.icloud.com/
    favicon: icloud.png
  - name: MEGA
    url: https://mega.nz/fm/
    favicon: mega.png
  - name: Wokers
    url: https://workers.cloudflare.com/playground
    # url: https://dash.cloudflare.com/?account=workers
    favicon: workers.png
  - name: Apps Script
    url: https://script.google.com/home
    favicon: appsscript.png
  - name: GDrive
    url: https://drive.google.com/drive/my-drive
    favicon: gdrive.png
  - name: OneDrive
    url: https://onedrive.live.com
    favicon: onedrive.png
  - name: Colab
    url: https://colab.research.google.com/notebooks/empty.ipynb
    favicon: colab.png
  - name: Vercel
    url: https://vercel.com/dashboard
    favicon: vercel.png
    faviconAlt: vercel_d.png
  - name: 百度网盘
    url: https://pan.baidu.com/disk/home
    favicon: baidunetdisk.png
  - name: 阿里云盘
    url: https://www.aliyundrive.com/drive
    favicon: aliyundrive.png
  - name: PikPak
    url: https://mypikpak.com/drive/all
    favicon: pikpak.png
  - name: 蓝奏云
    url: https://up.woozooo.com/

  - category: ACG
  - name: Danbooru
    url: https://danbooru.donmai.us/
    favicon: danbooru.png
  # - name: Gelbooru
  #   url: https://gelbooru.com/index.php?page=post&s=list&tags=user:danbooru
  #   favicon: gelbooru.png
  - name: yande.re
    url: https://yande.re/post
    favicon: yandere.png
  - name: Kemono
    url: https://kemono.su/artists
    favicon: kemono.png
  # - name: Sankaku
  #   url: https://sankaku.app/zh-CN
  # - name: Konachan
  #   url: https://konachan.com/post
  #   favicon: konachan.png
  - name: 番组计划
    #  url: https://bgm.tv/group/boring/forum # 靠谱人生茶话会
    url: https://bgm.tv/group/a/forum # ～技术宅真可怕～
  # - name: AcFun
  #   url: https://www.acfun.cn
  #   favicon: acfun.png
  # - name: 爱恋动漫
  #   url: https://www.kisssub.org/
  - name: Pixiv
    url: https://www.pixiv.net/bookmark_new_illust.php
    favicon: pixiv.png
  - name: 天使动漫
    url: https://www.tsdm39.com/forum.php
  - name: 萌娘百科
    url: https://zh.moegirl.org.cn/Mainpage
    favicon: moegirl.png
    faviconAlt: moegirl_d.png
  - name: 動漫花園
    url: https://share.dmhy.org
  # - name: 樱花动漫
  #   url: https://www.yinhuadm.one/
  #   favicon: cherryblossom.png
  # - name: Sukebei
  #   url: https://sukebei.nyaa.si/
  #   favicon: nyaa.png
  - name: Nyaa
    url: https://nyaa.si/
    favicon: nyaa.png
  - name: <b>More</b>
    newTab: true
    url: https://rentry.co/acg
    favicon: more.png

  - category: Audio
  - name: Spotify
    url: https://open.spotify.com/
    favicon: spotify.png
  - name: musicForProgramming
    url: https://musicforprogramming.net
  - name: Noises.online
    url: https://noises.online
  - name: AHA Music
    url: https://www.aha-music.com/upload

  - category: Calc
  - name: NumberEmpire
    url: https://zh.numberempire.com/
  - name: MathStudio
    url: http://mathstud.io
    favicon: mathstudio.png
  - name: Desmos
    url: https://www.desmos.com/calculator?lang=zh-CN
    favicon: desmos.png
    # Alternative
    # https://www.geogebra.org/graphing
  - name: Mathway
    url: https://www.mathway.com/zh/Algebra
    favicon: mathway.png

  - category: Life
  - name: 默沙东诊疗手册
    url: https://www.msdmanuals.cn/home
    favicon: merck.png
  - name: 12306
    url: https://www.12306.cn/index/
    favicon: railway12306.png
  #- name: 天气网
  #  url: http://www.weather.com.cn/
  #  favicon: cnweather.png
  - name: 天眼查
    url: https://www.tianyancha.com
    favicon: tianyancha.png
  - name: 企查查
    url: https://www.qcc.com
    favicon: qichacha.png
  - name: 历史价格查询
    url: https://www.lsjgcx.com


  - category: Unclassified
  - name: Applist
    newTab: true
    url: https://rentry.co/applist
    favicon: rentryco.png
  - name: NoUse
    newTab: true
    url: https://rentry.co/u6
  - name: LGUG
    newTab: true
    url: https://rentry.co/lgug
    favicon: rentryco.png
  - name: Github✋⭐
    url: https://rentry.co/githubnostar
    favicon: github.png
  - name: IMDb
    url: https://www.imdb.com
  - name: SteamDB
    url: https://steamdb.info
    favicon: steamdb.png
    faviconAlt: steamdb_d.png
  - name: MusicBrainZ
    url: https://musicbrainz.org/search
    favicon: musicbrainz.png
  - name: 福利吧
    url: https://fuliba.net

  # - category: NSFW
  # - name: E-Hentai
  #   url: https://e-hentai.org/
  # - name: ExHentai
  #   url: https://exhentai.org/
  # - name: 绅士仓库
  #   url: https://galacg.github.io/
  # - name: 琉璃神社⛩
  #   url: https://acg.gy/
  # - name: 紳士の庭🎩
  #   url: https://gmgard.com/
  # - name: HVDB
  #   url: https://hvdb.me/Dashboard/
  # - name: ＭＡＮＧＡ－ＤＢ
  #   url: https://adultcomic.dbsearch.net/
  # - name: 🐼Panda Backup
  #   url: https://panda.chaika.moe/
  # - name: 草榴社区
  #   url: https://t66y.com/index.php
  #   favicon: caoliu.png
  # - name: PornDude
  #   url: https://theporndude.com/zh
  #   favicon: porndude.png
